name: story_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: ^0.11.0+1
  camera_windows: ^0.2.5
  connectivity_plus: ^6.0.4
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.9+1
  http: ^1.2.2
  image: ^4.2.0
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  location: ^7.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/